### ISSUE TITLE
rendering issue with wireless crafting terminal

### ISSUE THREAD

**Issue by MasterSloth1** [p455w0rd/WirelessCraftingTerminal#323] opened 2019-03-02 00:12 UTC
I currently have the crafting terminal in my head bauble slot, it first started crashing my game when i was in the twilight forest hydra den i wasn't meant to be there so i was constantly on fire and weird particles flying around the place so i thought it was due to that so i teleported home then opened my inventory where a second crash happened.
yes i have a texture pack but i have used this texture pack in all my lets plays with no problems, it is sphax 64x with project ozone 3 addon

wireless crafting terminal - WirelessCraftingTerminal-1.12.2-3.11.88.jar
baubles - Baubles-1.12-1.5.2.jar
optifine - OptiFine_1.12.2_HD_U_E3.jar
forge - forge-14.23.5.2808
sponge - not really a number since I used the github version, i think its the one from feb 27 or 28 ( https://github.com/SpongePowered/SpongeForge/commits/stable-7 )

twilight forest crash
https://gist.github.com/MasterSloth1/658dac5a5c9835f6171aa3fe7fd36036
house crash
https://gist.github.com/MasterSloth1/0e2cac75f7254a00c6c2663a1a5235d9

**Comment by p455w0rd** [comment] 2019-03-11 13:45
dupe of #322

**Closed by p455w0rd** 2019-03-11 13:45 UTC
Labels: duplicate
