### ISSUE TITLE
[1.10.2] Beyond pack - WCT and EnderIO Wireless Charger (dupe)

### ISSUE THREAD

**Issue by artrorrr** [p455w0rd/WirelessCraftingTerminal#205] opened 2017-11-18 18:01 UTC
So... I noticed this when I got my items deleted form crafting grid and on the other had, my friend duped items in crafting grid.

From our troubleshoot we found that if you leave items in crafting grid when it is under 100% power and there is a wireless charger near re-charging it, after you close WCT grid it would retain grid content even after you take the items out and re-open the WCT - duping items. This also happens in reverse where your items get deleted.

It's hard to explain in words, but it's rally easy to replicate.
(Didn't test if it made diff, but WCT was in baubles slot)

MC - 1.10.2
WTC-0.1.32

**Comment by p455w0rd** [comment] 2017-11-18 18:13
duplicate of #160 - this has been fixed..you are running a really outdated version of WCT

**Closed by p455w0rd** 2017-11-18 18:13 UTC
Labels: duplicate
