### ISSUE TITLE
Broken GUI

### ISSUE THREAD

**Issue by GalacticWolf541** [p455w0rd/WirelessCraftingTerminal#197] opened 2017-11-05 18:43 UTC
This happens when I open the crafting terminal...
[https://imgur.com/kAzunzH](url)

Am I the only one or...?
Yes Ive restarted the game and optifine is NOT installed (anymore)

**Comment by p455w0rd** [comment] 2017-11-05 18:44
duplicate of #195

**Closed by p455w0rd** 2017-11-05 18:44 UTC
Labels: duplicate
