### ISSUE TITLE
Unable to remove/insert items into network using WCT

### ISSUE THREAD

**Issue by ratkinsonuk** [p455w0rd/WirelessCraftingTerminal#299] opened 2018-12-09 09:13 UTC
I'm unable to add or remove items through the Wireless Crafting Terminal. This is associated to the Automoton modpack, and I've also logged an associated issue request at https://github.com/rgtexa/Automaton/issues/26.

This works using the latest Automoton pack, but winding back to AE2 version rv5-11. The pack comes with AE2 rv6-3 on the latest version (version 1.5.0).

Let me know if you need a complete mod list, but you can obviously easily get that from downloading the pack from CurseForge.

Thanks, Rat

**Comment by p455w0rd** [comment] 2018-12-09 18:40
duplicate of #295

**Closed by p455w0rd** 2018-12-09 18:40 UTC
