### ISSUE TITLE
Booster Cards drops from Enderman, BUT the config say "no"

### ISSUE THREAD

**Issue by TheSnowyChickens** [p455w0rd/WirelessCraftingTerminal#222] opened 2018-01-05 01:34 UTC
Hello,

I was today in "The End" and I killed some Enderman and I was suprised about the booster cards they dropped, because I deactivate it in the configs ->

![config](https://user-images.githubusercontent.com/29357962/34591779-2913efce-f1c0-11e7-8274-971090214dd6.png)

![2018-01-05_02 31 13](https://user-images.githubusercontent.com/29357962/34591838-89894606-f1c0-11e7-9f20-cb4cc1be4888.png)

MC 1.12.2
Newest Version of your both mods ( WirelessCraftingTerminal-1.12.2-3.8.55 / p455w0rdslib-1.12-2.0.25 )
Forge 2583
-05.01.2018

I killed the Enderman with a Diamond Sword (In the Screen) and with a Tinkers' Sword with Looting (In my Play world)

**Comment by SDPhantom** [comment] 2018-01-12 09:35
Duplicate of #214 
Supposedly the fix is already in place, it's waiting for the next release.

**Comment by p455w0rd** [comment] 2018-01-24 17:36
yeah..was working with Drummer and the EC2 + WCT bug..I'll be doing releases for WCT, /dank/null, and ToughExpansion soon :) This is fixed in 3.8.56 (not on curse yet)

**Closed** 2018-02-06 17:04 UTC
Labels: bug, fixed in dev
