### ISSUE TITLE
Unable to Shift-Click NEI Crafting into Terminal (RV3 v1.8.4b)

### ISSUE THREAD

**Issue by NdMSnIpEz** [p455w0rd/WirelessCraftingTerminal#44] opened 2016-05-21 10:22 UTC
Even though this fix is mentioned in the changelogs, I'm still unable to shift click. I've completely removed the access point to save on my RF usage and the terminal works fine, but unable to shift click. I've tried this in various dimensions including the Last Millenium (where I had setup my AE system etc.) but to no avail.

Using a custom version of Infinity Evolved v2.4.2. I would update to v2.5.0 but don't want to mess up my custom configs. Here's a google sheet of the loadedmod dump so you can see if there may be any incompatabilities.

https://docs.google.com/spreadsheets/d/1ir5m_76qdN5oB6IcDK3pyAYBJaZkd1UVZycJ45Z-UNs/edit?usp=sharing

**Comment by p455w0rd** [comment] 2016-05-21 14:12
you should have to have an access point, so there is the real bug...I'll get this sorted asap

**Comment by NdMSnIpEz** [comment] 2016-05-21 16:19
Alright, I'll test it again once I get back home after adding an access point. Does this mean you would need an access point for every dimension or does it work cross-dimension?

**Comment by NdMSnIpEz** [comment] 2016-05-21 16:59
Maybe a workaround could be making the infinity card be used in the access terminal instead and use more power to balance it a little bit?

**Comment by p455w0rd** [comment] 2016-05-21 18:09
I don't see how it would be possible to create a new slot in the 'access' (Security?) terminal without asm hackery and I'm not going to do this. New features are at a halt until AE2 1.9 becomes a thing. I do have a lot of stuff planned, but I've moved on as the rest of the community should and I'm not looking back. Things will stay as they are with the exception of bugs and minor updates. The 1.9 version is going to have a major code overhaul as well as rebalancing. You will be required to have a stack of booster cards in a WAP of the network the WCT is linked to in order for the Booster Card to function for one. Also I will be doing away with the free cross dimension functionality and require a Quantum Bridge at minimum to be in the dimension you are in if it's not the same dimension as the linked network. People will hate me, but this mod really does go to extremes in ways I hadn't thought about until well after release. For now, I will fix this and the fix will be included in the next update which has some other stuff implemented as well. Thanks for reporting the bug. I will post here when the update is ready.

**Comment by p455w0rd** [comment] 2016-05-24 12:31
are you playing on a server? just test in IE 2.4.2 and had no issues shift-clicking even across dimensions

**Comment by p455w0rd** [comment] 2016-05-24 14:47
new version will be going up soon..if no reply, issue will be closed and assumed fixed since I am unable to reproduce bug

**Comment by p455w0rd** [comment] 2016-05-24 16:21
new version going up...if issue still persists (and it probably will since I couldn't reproduce the bug), you'll have to communicate with me better :/

**Comment by NdMSnIpEz** [comment] 2016-05-24 17:29
I'm playing in a single player world. Was unable to reply to your messages as I was at school when they were sent, apologies.

I have installed the update, and yes the issue does still persist. I can include a copy of the world file as well as a small video showing the issue.

I have my main AE system set up in the last millenium, then an access point in either dimension with a quantum ring to link the 2 dimensions. If I'm in the range of the access point, then the shift click works. 

The problem I'm having is that outside the range of the access points (using an infinity booster card), I'm unable to shift click. I have also noticed that the normal click to show the recipe from NEI (the ghost items) only works when in range of the access point.

Here is a log that is typical when trying to shift click: http://pastebin.com/6EbdXBS1
(You can view the full log here: http://paste.feed-the-beast.com/view/25cbed00)

The world file is here: (Will post link as soon as it's ready, mediafire takes a while)
Would upload to the post directly but it's 471MB, limit is 10MB.

The video is here: https://youtu.be/43Fe-xCAQUc

As I said, I'm using a heavily modified version of IE:E 2.4.2. 
Here is my full modlist: https://docs.google.com/spreadsheets/d/1ir5m_76qdN5oB6IcDK3pyAYBJaZkd1UVZycJ45Z-UNs/edit?usp=sharing. 

Finally, here's my system specs, just incase they are needed.
MB: MSI Z97 G43
CPU: i5 4690k
GPU: GTX 980Ti
PSU: EVGA Supernova G2 850W
SSD: Samsung Evo 850 500GB (the game is stored on here)
HDD: Seagate Barracuda 2TB (7200RPM)

Thanks for your patience.

**Comment by p455w0rd** [comment] 2016-05-24 18:08
you never mentioned that the shift-clicking you were talking about was the NEI shift-clicking. I thought you meant just shift-clicking items into the AE system...that would have helped...I'll see what I can do..

**Comment by NdMSnIpEz** [comment] 2016-05-24 18:18
Ah, I apologise - should of been more specific.

**Comment by p455w0rd** [comment] 2016-05-24 18:21
okay, I have reproduced the bug..working on it now..after I fix it, i'll release a hotfix update..Is there any way you could hop on IRC so I can let you test before I upload an official hotfix when it's ready? just go to https://esper.net/publicirc.php choose a name and in "channels" put #p455w0rdCraft

**Closed** 2016-05-24 19:58 UTC
Labels: fixed
