### ISSUE TITLE
1.1x+ Craft Amount GUI not showing (w/Video)

### ISSUE THREAD

**Issue by ronkkrop** [p455w0rd/WirelessCraftingTerminal#151] opened 2017-06-21 19:18 UTC
I originally posted this over on the AE2 github located here:
https://github.com/AppliedEnergistics/Applied-Energistics-2/issues/2934

After exhaustive troubleshooting, I've come to the conclusion that this issue only occurs when your mod is installed on the server.

> - Minecraft Version:  1.7.10
> - AE2 Version:  appliedenergistics2-rv2-stable-10
> - Forge Version:  I'm not sure...Here are the list of jar's within the 1.7.10 folder:
> ForgeMultipart-1.7.10-1.2.0.345-universal
> ForgeRelocation-0.0.1.4-universal
> ForgeRelocationFMP-0.0.1.2-universal
> 
> 
> After spending a considerable of time trying to learn AE2, I discovered that when an item, any item, is placed within a specific slot in your inventory, the autocraft window will close when you should be presented with a followup window asking how many you'd like to create.
> 
> Also, when something is placed in this inventory slot, when viewing 'Crafting Status' within the ME Crafting Terminal, the client will definitely crash and occasionally, the server will crash.
> 
> The inventory slot is 2nd row down, 4th from the left.
> 
> I wouldn't believe this report if I had seen it for myself, so I've included a video, where I go through a few different permutations in an attempt to rule out chance.
> 
> https://vid.me/CGQg
> 
> Should you need any further information, I'd be more than happy to offer whatever assistance I can.

**Comment by p455w0rd** [comment] 2017-06-21 22:37
![LET 1.7.10 DIE PLZ KTHX](http://p455w0rd.net/u/18.36.20-21.06.17.png "LET 1.7.10 DIE PLZ KTHX")

**Comment by ronkkrop** [comment] 2017-06-22 04:20
I posted this here because it exists in your current codebase if you'd bother to read the other bug report.

read here:

https://forum.feed-the-beast.com/threads/ae2-clicking-autocrafting-closes-inventory.240633/

**Comment by p455w0rd** [comment] 2017-06-22 04:49
Please remember when posting on mc mod issue trackers: We do this for free. I fail to see how I'm supposed to just assume that you mean all versions when you only specify 1.7.10 no matter what the other issue on another mod's tracker says.

see here:

![](http://memecrunch.com/meme/BIFJ1/stop-being-a-dick/image.jpg)

Still, I definitely appreciate your taking the time to research this and even make a video..I was kinda lost as to exactly how many slots/which caused this. I'll def get this handled in the next update. No ETA atm..I have a ton of stuff I'm working on atm not mention recovered from recent health issues. Please bare with me.

**Comment by ronkkrop** [comment] 2017-06-22 05:13
And i'm just a guy who came here on my time off to try to help you solve a bug in your codebase.  It's a minor bug.  I don't care if it gets fixed or not so there's no benefit to me.

**Comment by ronkkrop** [comment] 2017-06-22 05:21
I didn't read your bottom note.  I guess I poured gas on the fire.  I'm sorry about your health issues, I hope everything is better.

I just lost my job myself.   I read your original giant picture as a middle finger.  Perhaps I took that too harshly.

Best of luck friend.  I'll offer whatever help I can.

**Comment by ronkkrop** [comment] 2017-06-22 05:32
Thing is...it's not always that slot on that *level* (world, whatever you want to call it).  When I did it on my own server (which was the same world) it was 3rd from the left on the bottom row.  Now the thrown exception is within AE2's packet handling code.  So I'm guessing your addon hooks into AE2 there?

If you're going to look into it...  You should note that the other bug report contains the caught exception for when I dropped out there.

And again, if it helps, I'm willing to help out with whatever testing you require....just note that for me, I'm running 1.7.10.

**Comment by p455w0rd** [comment] 2017-06-22 05:46
cool..the crash log should definitely help, thanks again

**Comment by JasonMcRay** [comment] 2017-06-27 16:35
it looks like totally same issue as was present in 1.7 (https://github.com/p455w0rd/WirelessCraftingTerminal/issues/72) :(

**Comment by p455w0rd** [comment] 2017-06-28 02:01
I'm swamped with stuff atm, I will get to this as soon as I can. All of the settings that were at one point saved, seem to now not be saving..something got borked somewhere down the line..thanks for the reports..sorry I can't do it any faster.

**Comment by p455w0rd** [comment] 2017-08-07 05:03
is this still happening on latest version on curse (v0.1.32)?

**Comment by ronkkrop** [comment] 2017-08-07 07:33
Unfortunately I won't be able to test this update for a few days, maybe up to a week as I'm out of town.  When I'm back, I'll put it in my test server and see.  Thanks for the update.

**Comment by p455w0rd** [comment] 2017-08-07 10:31
No worries, test when you have time :) @JasonMcRay I owuld like your input on this as well if you can find the time.

**Comment by p455w0rd** [comment] 2017-09-27 13:00
I would really like to get _someone_ experiencing this to try and help fix the problem..I have tested and tested and I can't reproduce this bug. I'm going to close the issue as I haven't gotten any replies...You're more than welcome to reopen if you wish to help me in being able to reproduce this bug.

**Closed by p455w0rd** 2017-09-27 13:00 UTC
Labels: bug

**Comment by Fapiko** [comment] 2018-01-03 22:26
I recently encountered this as well and have done some testing to figure out why only 2 of my terminals were crashing when others in my void dimension were working fine. It appears that it only affects terminals which are placed in the portal chunk of the Void dimension get affected by this bug (at least for me).
