### ISSUE TITLE
sudden crash

### ISSUE THREAD

**Issue by Kern07** [p455w0rd/WirelessCraftingTerminal#357] opened 2019-10-31 08:19 UTC
https://paste.dimdev.org/inoliyasuw.mccrash

[crash-2019-10-31_09.13.14-client.txt](https://github.com/p455w0rd/WirelessCraftingTerminal/files/3792789/crash-2019-10-31_09.13.14-client.txt)

**Comment by Kern07** [comment] 2019-10-31 08:24
it happens when I put an item in the wireless terminal.

**Comment by Wheelz86** [comment] 2019-10-31 08:44
Same here... Something to do with the *happy halloween* message?

`Time: 10/31/19 9:33 AM
Description: Updating screen events

java.lang.ClassCastException: net.minecraft.entity.monster.EntityWitherSkeleton cannot be cast to net.minecraft.entity.player.EntityPlayer
	at p455w0rd.wct.client.gui.GuiWCT.func_146273_a(GuiWCT.java:275)
	at net.minecraft.client.gui.GuiScreen.func_146274_d(GuiScreen.java:548)
	at p455w0rd.wct.client.gui.GuiWCT.func_146274_d(GuiWCT.java:157)
	at net.minecraft.client.gui.GuiScreen.func_146269_k(GuiScreen.java:501)
	at net.minecraft.client.Minecraft.func_71407_l(Minecraft.java:1759)
	at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:1098)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:398)
	at net.minecraft.client.main.Main.main(SourceFile:123)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)`

**Comment by Immow** [comment] 2019-10-31 11:13
same for me

**Comment by p455w0rd** [comment] 2019-11-09 15:07
dupe of #356

**Closed by p455w0rd** 2019-11-09 15:07 UTC
Labels: duplicate
