### ISSUE TITLE
WCT not showing items in network properly

### ISSUE THREAD

**Issue by Hazmatik** [p455w0rd/WirelessCraftingTerminal#127] opened 2017-04-05 12:58 UTC
After updating FTB Beyond from 1.1.0 to 1.4.0 
(WCT Versions 0.0.16 -> 0.1.25)
The WCT is now only showing the items in the network after more of those items are added into the network and is resetting every time I open it.

GIF 1: I open the terminal and it's empty then items start coming into the network from my void miner and my ore processing
https://i.gyazo.com/2371152d3ee3822a906a4793bdc08fc8.gif

GIF 2: Closing and re-opening same thing empty at first until items come in then it displays only those items
https://i.gyazo.com/12557c455e5fbd7e24975063bd097cfa.gif

View of items actually on the network through AE2 Crafting Terminal:
https://i.gyazo.com/3a763c7ab5a9197bf5bc69c4ade895f5.png

I tried crafting a new WCT and linking it and the same issue occurred

FTB Beyond: 1.4.0
WCT version: 0.1.25
AE2 version: rv4-alpha-11

**Comment by NikitaSmolin** [comment] 2017-04-05 16:24
same problem :(

**Comment by p455w0rd** [comment] 2017-04-05 18:15
is this a SMP-only problem?

**Comment by p455w0rd** [comment] 2017-04-05 18:49
just tested in a dedicated server environment using only the necessary mods and couldn't reproduce...testing with Beyond now

**Comment by p455w0rd** [comment] 2017-04-05 18:57
please give me details of what your setup is...I am not able to reproduce this at all

**Comment by Hazmatik** [comment] 2017-04-05 20:55
Well I tested in singleplayer and the issue doesn't reproduce so it may be a problem with the server.

**Comment by p455w0rd** [comment] 2017-04-05 21:55
hmm..does this happen with the AE2 wireless terminal as well?

**Comment by p455w0rd** [comment] 2017-04-05 21:57
if so, it would be worth looking into this: https://forums.spongepowered.org/t/spongebootstrap-fixes-ordering-issue-with-other-coremods/12275 - it forces Sponge's core stuff to load before any other mod's which seems to fix a lot of the AE2<->Sponge conflicts

**Comment by Hazmatik** [comment] 2017-04-06 00:49
The AE2 Wireless terminal works as normal

**Comment by p455w0rd** [comment] 2017-04-16 05:23
is this still happening? i can't reproduce this

**Comment by p455w0rd** [comment] 2017-04-18 02:26
closing for now..if you are still experiencing this, just reply and I'll reopen and we can look into this further

**Closed by p455w0rd** 2017-04-18 02:26 UTC
Labels: bug, unable to reproduce
