### ISSUE TITLE
Crash when activating Magnet Card (in Creative WCT)

### ISSUE THREAD

**Issue by BrisingrAerowing** [p455w0rd/WirelessCraftingTerminal#235] opened 2018-02-16 06:43 UTC
[Crash Log](https://gist.github.com/BrisingrAerowing/0cb5079eef4d4ffc67f15588b754e1a4)

I tried activating the magnet card by clicking the button in the WCT GUI, and that happened.

WCT: 3.9.59

**Comment by p455w0rd** [comment] 2018-02-16 14:13
I've tried in SSP, SMP with old infinity mechanic enabled and disabled and cannot reproduce

**Comment by BrisingrAerowing** [comment] 2018-02-16 17:26
I'll mess around with it and see what I can find.

**Comment by BrisingrAerowing** [comment] 2018-02-16 17:32
Doesn't `getTagCompound` return null when there is no NBT on the item? The item I have doesn't have a tag (as noted in the tooltip). Since you don't check it for null, there is potential for this to happen.

**Comment by p455w0rd** [comment] 2018-02-16 17:38
this is a good point..dammit..I already pushed the update..so the magnet gets initialized at different possible points, but not on creation..if you view the settings GUI (either by crouch+right-click or the button above the slot in WCT) it will be initialized with the NBT data..the update that is pushed will not crash , but it also doesn't initialize it at the point where it catches the null..I'll make a new issue to remind me to just initialize the magnet rather than just ignoring the null at that point in code.

**Closed by p455w0rd** 2018-02-16 17:38 UTC

**Comment by p455w0rd** [comment] 2018-02-16 17:42
can u hop on discord briefly?
