### ISSUE TITLE
Wireless Crafting terminal, Cannot remove or place items in. 

### ISSUE THREAD

**Issue by Craken761** [p455w0rd/WirelessCraftingTerminal#293] opened 2018-10-29 12:11 UTC
When using the wireless crafting terminal, I can see items, but am unable to pull items out or place items into the system. I am strangely able to remove half a stack at a time by right clicking. 

This error might be modpack specific, as the issue has also been added here https://github.com/EmosewaPixel/Modern-Skyblock-3/issues/797

The above issue is more detailed with server logs.

**Comment by BrockWS** [comment] 2018-10-29 12:14
Duplicate of #282. Update WCT to 3.10.82

**Closed** 2018-10-29 14:38 UTC
Labels: duplicate
