### ISSUE TITLE
Magnet card not inserting items into network.

### ISSUE THREAD

**Issue by Hazmatik** [p455w0rd/WirelessCraftingTerminal#124] opened 2017-03-30 15:48 UTC
I've tried both settings for the card when I have some of the item in the network and I drop some on the ground the magnet card picks it up and puts it in my player inventory and not into the network. I tried filling my player inventory and then dropping the items it just doesn't pick them up at all. Thought it could have been an issue with Sponge cause the server I play on uses it but I also tested in singleplayer with the same results.
This is on FTB Beyond 1.1.0

**Comment by p455w0rd** [comment] 2017-03-30 16:01
open the gui and set it to blacklisting

**Comment by Hazmatik** [comment] 2017-03-30 16:38
Ok, I did that and it worked. I did notice though if i had less than a full stack of the item still in my player inventory it put the items there instead of in the system.

**Comment by p455w0rd** [comment] 2017-03-30 17:03
okay, I'll mark this as a bug for now and try to reproduce..working on finding the culprit behind #123 atm

**Comment by Hazmatik** [comment] 2017-03-30 17:06
I noticed it will only fill the stack in the players inventory and the rest goes into the system. For example if I have 1 1/2 stacks of dirt and I drop the whole stack 32 go into the system and the other 32 fill up the 1/2 stack that is still in my inventory.

**Comment by p455w0rd** [comment] 2017-03-30 19:07
mind joining my discord at https://discord.gg/9J7yhUP ? I have a version I'd like for you to test for me

**Comment by p455w0rd** [comment] 2017-04-03 21:12
Can you confirm whether or not this is still happening in the latest version (0.1.25) please

**Comment by p455w0rd** [comment] 2017-04-03 23:12
I'm going to close this for now as I can't reproduce, just comment if you still experience this.

**Comment by Zovoka** [comment] 2017-04-27 04:08
Version: 0.1.27

This bug occurs for me when joining the server from a lobby server on a multiplayer server with realms. The bug is fixed after a server restart as far as I can tell. Changing between leave on ground and put in inventory does not effect the result. It can only be turned off entirely. Resetting the me system or replacing the security terminal and reconnecting the terminal do not fix it.

**Comment by p455w0rd** [comment] 2017-04-27 04:17
try a more recent version (0.1.31 is latest atm) please and tell me if you still experience this

**Comment by stensch** [comment] 2017-06-02 15:11
I have the same problem with 0.1.31

**Comment by armrha** [comment] 2018-01-04 03:52
I just encountered this bug with 3.8.55. It was working on multiplayer, I downloaded that save to fix an unrelated issue with a tesselating block crash bug, re-uploaded that world save to the multiplayer and now it appears broken. Any idea what the issue might be there? 

I also notice I cannot remove the infinity card after I put it into the controller, not sure if that is the default behavior, I don't remember trying to remove it before. Blacklist, whitelist, leave on ground or add to inventory, it still pulls items toward me while active but isn't inserting them into the inventory. Thanks p455w0rd, love the mod.

**Comment by armrha** [comment] 2018-01-04 10:11
It turned out to be very simple. I should not have loaded the world single player, that put my data into level.dat, and the wireless terminals were unable to find the network to insert into with the conflicting information. If anyone else has this probably very rare problem, just use NTBexplorer on level.dat to delete the ‘player’ field and your WCTs will work again in multi after you put the modified level.dat back.

**Comment by ZackZeed** [comment] 2019-01-25 22:43
I have a similar problem like the one Hazmatik has But i have more glitches/bugs then that. For one, when i want to blacklist/whitelist an item or a block in the magnet card it resets when i close the Gui and so far i could only fix this Partially through leaving and joining my server again.
And no items/blocks are automaticly placed in the AE network.
The only thing that Did seem to work was the magnet mode (items that were whitelisted got sucked into the inventory)

I have quite a few mods installed in my modpack, for exmaple baubles, AE (duh) and Cyclic who change/upgrade the inventory.

**Comment by p455w0rd** [comment] 2019-01-26 01:12
Just tested SSP and SMP..it works as it should - [video (SMP test)](https://puu.sh/CCohm/535bb37cd1.webm)

**Comment by ZackZeed** [comment] 2019-01-26 02:52
I recorded a very short video too show you kidna what i mean but how can i send it to you? i also could just upload it to yt real quick.

**Comment by p455w0rd** [comment] 2019-01-26 02:54
DM me on discord https://discord.gg/9J7yhUP

**Comment by BanzaiRun** [comment] 2019-04-23 23:57
1.12.2

Not sure if this is part of this issue but when a drawer is broken with more than a stack in it, the items "added" disappear from the system. 
There IS a storage bus on the drawer controller and I'm wondering is its actually AE adding the items to the drawer which now no longer exists.
Having typed this and read it, I'm even more convinced that this isn't anything to do with you.
Hmmm, I'm going to disable the storage bus and try that again...
Yeah, it's the storage bus not updating fast enough.
Well I suppose if your magnet wasn't quite soooo quick...
I'll sneak /shrug
:)

**Comment by p455w0rd** [comment] 2019-04-24 00:34
@BanzaiRun it supports demagnetize mod..

**Comment by BanzaiRun** [comment] 2019-04-24 01:13
Yeah, but that's no fun when you want to suck in 10k items
:)

**Comment by BanzaiRun** [comment] 2019-04-25 13:54
@p455w0rd Just to clarify, that's what I meant by "I'll sneak", or did you mean something else?

**Closed** 2019-05-24 20:32 UTC
Labels: bug
