### ISSUE TITLE
Not Compatible with mekanism

### ISSUE THREAD

**Issue by maxkilic** [p455w0rd/WirelessCraftingTerminal#232] opened 2018-01-29 07:25 UTC
Client Crashlog

https://pastebin.com/fhwqs6fZ

Server Crashlog

https://pastebin.com/CN4R5uik

**Comment by p455w0rd** [comment] 2018-01-29 13:11
duplicate of #229 this is on extracells end, drummer has fixed it, up to him as to if/when he uploads an update to curseforge

**Closed by p455w0rd** 2018-01-29 13:11 UTC
