### ISSUE TITLE
Magnet Mode not properly updating when used as Bauble and being charged via EIO Wireless Charger/Antenna

### ISSUE THREAD

**Issue by Revvilo** [p455w0rd/WirelessCraftingTerminal#284] opened 2018-09-20 03:28 UTC
No clue if this is on Ender IO's end or here, so I'm just starting here.
## Issue
When having the WCT in a Baubles slot, within the range of an Ender IO Charging Antenna, the NBT for the WCT's crafting grid will not update when changed via the GUI. Creating either an item deletion bug, or an immensely powerful item duplication bug.
## Reproduction
- Create a setup similar to this:
<img src="https://user-images.githubusercontent.com/13816212/45793603-13c5d680-bce7-11e8-992a-d7bdf7715d6f.png" width="200px">

- Link the WCT to the security terminal
- Place the WCT in a Baubles slot
- Open the WCT via the hotkey
- Place an item inside the crafting grid
- Close and reopen the WCT, the item should have disappeared.

To duplicate instead of delete, simply place an item inside the WCT before putting it inside a Baubles slot. Reopening the GUI will create more items again.
## Notes
- This happens with ALL of the Ender IO wireless chargers
#### Latest affected mod versions
| Minecraft - 1.12.2 | |
|---|---|
| AE2 | rv6-alpha-4 |
| Baubles | 1.5.2 |
| Ender IO | 5.0.33 |
| Ender Core | 0.5.39 |
| p455w0rd's Library | 2.0.35 |
| Wireless Crafting Terminal | 3.10.81 |

**Comment by p455w0rd** [comment] 2018-09-20 03:38
thank you for the amazingly detailed report..they are all too rare nowadays! sounds legit, so I'll mark it as a bug and stream fixing it tomorrow..thank you!

**Comment by p455w0rd** [comment] 2018-09-21 19:43
any chance you could drop by my stream? trying to replicate this right now, but i've tried everything and nothing is working...the WCT just works as intended for me

**Comment by p455w0rd** [comment] 2018-09-21 19:52
tried everything and after reading what you put here several times it just doesn't make any sense...going to close this and mark it as invalid until you can show a video or something

**Comment by Revvilo** [comment] 2018-09-21 22:37
Sorry, I was checking all day for the stream but still didn't manage to catch it.
I'll most definitely make a video or gif if needed. Was there any particular problem with the explanation?

**Comment by Revvilo** [comment] 2018-09-21 23:13
Ok, so I looked back on the stream and found what I think to be the problem.

As far as I can tell, all of the wireless chargers search your inventory for something to charge - once it finds something, it charges it until full and moves on to the next chargeable item in your inventory.
Problem is, the creative capacitor is half full permanently, thus it sucks all wireless power **as long as it is the thing being charged**.

In the stream's case, you found that it was charging while in your hotbar, **but not as a Bauble**.
When it was simply the fact that when you moved it to the Baubles, the creative capacitor was then **proceeding** the WCT and sucking all the power.

<img src="https://user-images.githubusercontent.com/13816212/45909760-ff551b80-be57-11e8-8d40-80372140832e.png" width="250px">

So I think the reason you couldn't reproduce it was because of that.
The very issue itself requires the WCT being used as a Bauble, AND being charged wirelessly.

I hope that clears it up. Sorry I couldn't have helped at the time...

**Comment by p455w0rd** [comment] 2018-09-22 18:06
reproduced..thanks..will work on it

**Comment by p455w0rd** [comment] 2018-09-22 18:29
you're welcome to hop on my discord if u want a version with this fixed...it'll be a min before i push to github/curse - http://p455w0rd.net/discord

**Comment by Revvilo** [comment] 2018-09-27 23:37
Hey, sorry to revive this, and I really appreciate the work you've done (it's so nice having a safe terminal back 😃) but maybe more of a blanket solution is needed, as it is still behaving the same way with the Magnet Card's button in the GUI.
Clicking the button will visually change it and say (in chat) that it has changed, but will not change the actual magnet's behavior, and then reopening the GUI will show that it's still set to the mode you started with.
I assume it's related, as it happens under the same conditions (with the wireless charger), so hopefully it's an easy fix.

**Comment by p455w0rd** [comment] 2018-09-28 00:29
not 100% sure what's going on tbh, but I have reproduced the magnet mode bug..I'll work on it..thx for reporting :D

**Closed** 2018-12-18 01:38 UTC
Labels: bug, fixed
