### ISSUE TITLE
Auto Crafting GUI Not Showing UP

### ISSUE THREAD

**Issue by Ronaldi2001** [p455w0rd/WirelessCraftingTerminal#64] opened 2016-06-04 03:06 UTC
Hi @p455w0rd, I am using your mod in my modpack that i am playing with and I noticed after you said that this problem was fixed in the AE2 Github #[2270](https://github.com/AppliedEnergistics/Applied-Energistics-2/issues/2270) But ive been playing and this problem keeps happening.

**Comment by p455w0rd** [comment] 2016-06-04 03:09
need info...what ae2 version, what WCT, offline/SMP, etc..any relevant info you can provide as everything works for me..what pack? if a custom pack, then mod list..perhaps even upload a copy of fml-client-latest.log to pastebin and post the link...thanks for the report!

**Comment by Ronaldi2001** [comment] 2016-06-04 12:32
I am plating in a single player world.
I am playing in a custom modpack that I made for just me.
[fml-client-latest.log](https://raw.githubusercontent.com/Ronaldi2001/WCT-Bug/master/fml-client-latest.log)

Applied Energistics Mods:
AE2: aapliedenergistics2-rv3-beta-6.jar
WCT: WirelessCraftingTerminal-1.7.10-rv3-1.8.6.2b.jar
AE2 Stuff: ae2stuff-rv3-.5.1.9-mc1.7.10.jar

**Comment by p455w0rd** [comment] 2016-06-09 16:15
I have tested extensively and cannot reproduce this, therefore I am unable to create a fix for it. Try creating a new instance and only include ae2, wct, and ae2stuff, then create a new world and tell me if thbe problem persists. for now I will close this issue in hopes that someone might create a new issue if they have the same problem.

**Closed by p455w0rd** 2016-06-09 16:15 UTC
Labels: unable to reproduce
