### ISSUE TITLE
StackOverflowError crash

### ISSUE THREAD

**Issue by Sir-Will** [p455w0rd/WirelessCraftingTerminal#254] opened 2018-04-24 23:57 UTC
If you open a wireless crafting terminal and insert an item into the terminal using the number keys, it has a chance on crashing the server and then the terminal disappears.

Also this way you can insert the terminal in the terminal, and then when you take it out, it crashes.
```
java.lang.StackOverflowError: Ticking player
	at net.minecraft.nbt.NBTBase.equals(SourceFile:129)
	at net.minecraft.nbt.NBTTagCompound.equals(NBTTagCompound.java:459)
	at java.util.Objects.equals(Objects.java:59)
	at java.util.HashMap$Node.equals(HashMap.java:311)
	at java.util.HashMap$EntrySet.contains(HashMap.java:1021)
	at java.util.AbstractCollection.containsAll(AbstractCollection.java:318)
	at java.util.AbstractSet.equals(AbstractSet.java:95)
	at java.util.Objects.equals(Objects.java:59)
	at net.minecraft.nbt.NBTTagCompound.equals(NBTTagCompound.java:459)
	at java.util.Objects.equals(Objects.java:59)
	at java.util.HashMap$Node.equals(HashMap.java:311)
	at java.util.HashMap$EntrySet.contains(HashMap.java:1021)
	at java.util.AbstractCollection.containsAll(AbstractCollection.java:318)
	at java.util.AbstractSet.equals(AbstractSet.java:95)
	at java.util.Objects.equals(Objects.java:59)
....
```

WirelessCraftingTerminal-1.12.2-3.9.64

**Comment by p455w0rd** [comment] 2018-04-25 00:06
i will need more than this from the crash log

**Comment by Sir-Will** [comment] 2018-04-25 02:37
https://pastebin.com/ePQVWUyM

**Comment by p455w0rd** [comment] 2018-04-25 12:14
ok, so I'm testing with only AE2, WCT, and pwlib in Twitch Desktop...that last update fixed this problem..I also have integration with MouseTweaks and ItemScroller (they are disabled for WCT's GUI)...this simply isn't possible without another mod messing with key input..can you please set up an instance with only these core mods and see if you can reproduce?

**Comment by p455w0rd** [comment] 2018-06-04 17:30
closing due to lack of communication

**Closed by p455w0rd** 2018-06-04 17:30 UTC
