### ISSUE TITLE
Void world deleted items

### ISSUE THREAD

**Issue by 47delasPECII** [p455w0rd/WirelessCraftingTerminal#253] opened 2018-04-23 05:30 UTC
My base in in a void world from the mod Simple Void World (modmuss50) and i have there my AE sistem with the WirelessCraftingTerminal-1.12.2-3.9.64.jar if i put items in the WCT gui to craft something and close the WCT gui the itemes get deleted.

**Comment by p455w0rd** [comment] 2018-06-20 15:12
dupe of #250

**Closed by p455w0rd** 2018-06-20 15:12 UTC
Labels: duplicate
