### ISSUE TITLE
[1.10.2] Crash on start game

### ISSUE THREAD

**Issue by medinasgaider** [p455w0rd/WirelessCraftingTerminal#233] opened 2018-02-02 19:34 UTC
Hello, when I start the game using the mod (WirelessCraftingTerminal-1.10.2-2.1.41.jar), I get the following error and the game does not start. Apparently some problem with the mekanism. If I alter you have any idea what might be causing the problem, I appreciate the help!

Follow the log with the error:

net.minecraftforge.fml.common.LoaderExceptionModCrash: Caught exception from Mekanism (Mekanism)
Caused by: java.lang.NoSuchMethodError: p455w0rd.wct.api.WCTApi.items()Lp455w0rd/wct/api/IWCTItems;
	at extracells.integration.WirelessCrafting.WirelessCrafting$.getCraftingTerminal(WirelessCrafting.scala:25)
	at extracells.util.UniversalTerminal$.<init>(UniversalTErminal.scala:41)
	at extracells.util.UniversalTerminal$.<clinit>(UniversalTErminal.scala)
	at extracells.util.recipe.RecipeUniversalTerminal$$anonfun$matches$1.apply$mcVI$sp(RecipeUniversalTerminal.scala:42)
	at scala.collection.immutable.Range.foreach$mVc$sp(Range.scala:160)
	at extracells.util.recipe.RecipeUniversalTerminal$.func_77569_a(RecipeUniversalTerminal.scala:30)
	at mekanism.common.util.MekanismUtils.findMatchingRecipe(MekanismUtils.java:1366)
	at mekanism.common.integration.OreDictManager.addLogRecipes(OreDictManager.java:368)
	at mekanism.common.integration.OreDictManager.init(OreDictManager.java:40)
	at mekanism.common.Mekanism.postInit(Mekanism.java:1424)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at net.minecraftforge.fml.common.FMLModContainer.handleModStateEvent(FMLModContainer.java:616)
	at sun.reflect.GeneratedMethodAccessor3.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at com.google.common.eventbus.EventSubscriber.handleEvent(EventSubscriber.java:74)
	at com.google.common.eventbus.SynchronizedEventSubscriber.handleEvent(SynchronizedEventSubscriber.java:47)
	at com.google.common.eventbus.EventBus.dispatch(EventBus.java:322)
	at com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:304)
	at com.google.common.eventbus.EventBus.post(EventBus.java:275)
	at net.minecraftforge.fml.common.LoadController.sendEventToModContainer(LoadController.java:243)
	at net.minecraftforge.fml.common.LoadController.propogateStateMessage(LoadController.java:221)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at com.google.common.eventbus.EventSubscriber.handleEvent(EventSubscriber.java:74)
	at com.google.common.eventbus.SynchronizedEventSubscriber.handleEvent(SynchronizedEventSubscriber.java:47)
	at com.google.common.eventbus.EventBus.dispatch(EventBus.java:322)
	at com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:304)
	at com.google.common.eventbus.EventBus.post(EventBus.java:275)
	at net.minecraftforge.fml.common.LoadController.distributeStateMessage(LoadController.java:145)
	at net.minecraftforge.fml.common.Loader.initializeMods(Loader.java:810)
	at net.minecraftforge.fml.client.FMLClientHandler.finishMinecraftLoading(FMLClientHandler.java:334)
	at net.minecraft.client.Minecraft.func_71384_a(Minecraft.java:520)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:351)
	at net.minecraft.client.main.Main.main(SourceFile:124)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.multimc.onesix.OneSixLauncher.launchWithMainClass(OneSixLauncher.java:196)
	at org.multimc.onesix.OneSixLauncher.launch(OneSixLauncher.java:231)
	at org.multimc.EntryPoint.listen(EntryPoint.java:143)
	at org.multimc.EntryPoint.main(EntryPoint.java:34)

I'm using:
WirelessCraftingTerminal-1.10.2-2.1.41.jar
p455w0rdslib-1.10.2-1.0.30.jar
Mekanism-1.10.2-9.2.4.103.jar

**Comment by p455w0rd** [comment] 2018-02-02 19:35
duplicate of #232 - @DrummerMC knows about this and is/will be fixing..it's due to the version of WCT he was building against

**Closed by p455w0rd** 2018-02-02 19:35 UTC

**Comment by medinasgaider** [comment] 2018-02-02 21:33
Thanks!
