### ISSUE TITLE
Cards disappear after adding them to the terminal

### ISSUE THREAD

**Issue by belnumcree** [p455w0rd/WirelessCraftingTerminal#337] opened 2019-06-02 18:59 UTC
Playing Project Ozone 3. When I add infinity booster or magnet card they disappear from their slots after exiting the terminal.

**Comment by p455w0rd** [comment] 2019-11-13 15:32
I am unable to reproduce after all my testing. So at minimum, this should be fixed in the coming update.

**Closed by p455w0rd** 2019-11-13 15:32 UTC
