### ISSUE TITLE
[1.12.2] crash with your lib

### ISSUE THREAD

**Issue by TheSnowyChickens** [p455w0rd/WirelessCraftingTerminal#189] opened 2017-10-23 23:43 UTC
Hello,
I updated your lib and then this happend:

"The game crashed whilst there was a severe problem during mod loading that has caused the game to fail
The game crashed whilst there was a severe problem during mod loading that has caused the game to fail
Error: net.minecraftforge.fml.common.LoaderExceptionModCrash: Caught exception from Wireless Crafting Terminal 2 (wct)"

Crashlog -> https://pastebin.com/AGj7PHGF

MC 1.12.2
WirelessCraftingTerminal-1.12.2-3.5.45
p455w0rdslib-1.12-2.0.22
Forge 2515

**Comment by HachiroMC** [comment] 2017-10-24 01:34
Same here... had a crash after updating your lib...

Minecraft
  - v1.12.2
Forge
  - 1.12.2-14.23.0.2515
Wireless Crafting Terminal
  - WirelessCraftingTerminal-1.12.2-3.5.45 (beta)
p455w0rd's Library
  - p455w0rdslib-1.12-2.0.22

[crash-2017-10-23_18.58.48-client.txt](https://github.com/p455w0rd/WirelessCraftingTerminal/files/1409240/crash-2017-10-23_18.58.48-client.txt)

**Comment by p455w0rd** [comment] 2017-10-24 15:17
duplicate of #188

**Closed by p455w0rd** 2017-10-24 15:17 UTC
